            - name: Build with Gradle
  # You may pin to the exact commit or the version.
  # uses: gradle/actions@417ae3ccd767c252f5661f1ace9f835f9654f2b5
  uses: gradle/actions@v3.1.0

name: Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Build with Gradle
      run: ./gradlew build
