            - name: Compiling Minecraft Mod
  # You may pin to the exact commit or the version.
  # uses: RuochenFu21/compilation@6bb9ada03c2d3c12f45ed3eb2cf1d70d60cf0814
  uses: RuochenFu21/compilation@v1

name: Compiling

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Compile
      uses: Ruochenfu2011/compilation@v1
      
    - name: Archive Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Artifacts
        path: ./build/libs
